#ifndef COMMAND_IDS_H
#define COMMAND_IDS_H 1

#define CMD_STOP_PERSISTENCE  0x80
#define CMD_START_PERSISTENCE 0x81
#define CMD_SET_FLUSH_PARAM   0x82
#define CMD_SET_VBUCKET       0x83
#define CMD_GET_VBUCKET       0x84
#define CMD_DEL_VBUCKET       0x85

#define CMD_START_REPLICATION 0x90
#define CMD_STOP_REPLICATION  0x91
#define CMD_SET_TAP_PARAM     0x92
#define CMD_EVICT_KEY         0x93

#endif /* COMMAND_IDS_H */
