/*
 *     Copyright 2022-Present Couchbase, Inc.
 *
 *   Use of this software is governed by the Business Source License included
 *   in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
 *   in that file, in accordance with the Business Source License, use of this
 *   software will be governed by the Apache License, Version 2.0, included in
 *   the file licenses/APL2.txt.
 */

#include <executor/globaltask.h>
#include <memcached/stat_group.h>

StatsGroupManager::StatsGroupManager()
    : entries({
              {.id = StatGroupId::All,
               .key = "",
               .description = "Get the common stats. Users holding the Stats "
                              "privilege may request system statistics without "
                              "a bucket context",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Reset,
               .key = "reset",
               .description =
                       "For dev and test use only. Using the reset command in "
                       "production can cause production problems, as well as "
                       "the inability to diagnose issues. The reset command is "
                       "not a single atomic operation; therefore, threads may "
                       "keep updating some stats while the reset operation is "
                       "causing others to be cleared. This can cause overflows "
                       "for calculated values and other stats used by the "
                       "cluster",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::WorkerThreadInfo,
               .key = "worker_thread_info",
               .description = "Information about the worker threads",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Audit,
               .key = "audit",
               .description = "Audit subsystem",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::BucketDetails,
               .key = "bucket_details",
               .description = "Bucket subsystem",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Connections,
               .key = "connections",
               .description = "Connection subsystem",
               .privileged = false,
               .bucket = false,
               .task_id = TaskId::Core_StatsConnectionTask},
              {.id = StatGroupId::ClientConnectionDetails,
               .key = "client_connection_details",
               .description = "Information of clients connected to the system",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsConnectionTask},
              {.id = StatGroupId::Clocks,
               .key = "clocks",
               .description = "Clock information",
               .privileged = false,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::JsonValidate,
               .key = "json_validate",
               .description = "Timings related to JSON validation",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::SnappyDecompress,
               .key = "snappy_decompress",
               .description = "Timings related to Snappy inflate",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::SubdocExecute,
               .key = "subdoc_execute",
               .description = "Timings related to subdoc execution",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Responses,
               .key = "responses",
               .description = "The number of various response codes",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Tracing,
               .key = "tracing",
               .description = "Tracing information",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Allocator,
               .key = "allocator",
               .description = "Memory internal allocation statistics",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Scopes,
               .key = "scopes",
               .description = "Stats for all scopes or a single scope (using "
                              "scope name as a key)",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::ScopesById,
               .key = "scopes-byid",
               .description = "Stats for a single scope using the id as a key",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::ScopesDetails,
               .key = "scopes-details",
               .description = "Detailed vbucket-level stats for all scopes, "
                              "for one or all vbuckets",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Collections,
               .key = "collections",
               .description = "Stats for all collections or a single "
                              "collection (using collection name as a key)",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::CollectionsById,
               .key = "collections-byid",
               .description =
                       "Stats for a single collection using the id as a key",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::CollectionsDetails,
               .key = "collections-details",
               .description = "Detailed vbucket-level stats for all "
                              "collections, for one or all vbuckets",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::TasksAll,
               .key = "tasks-all",
               .description = "Get information from the tasks in the executor "
                              "pool for all Taskables",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::ExternalAuthTimings,
               .key = "external-auth-timings",
               .description = "Histograms including external auth response "
                              "times for various server opcodes",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Uuid,
               .key = "uuid",
               .description = "Get the UUID for the bucket",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              // epe specifics
              {.id = StatGroupId::Dcpagg,
               .key = "dcpagg",
               .description = "Get aggregated DCP stats",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Dcp,
               .key = "dcp",
               .description = "Get DCP related stats",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::EncryptionKeyIds,
               .key = "encryption-key-ids",
               .description = "Get the encryption key identifiers in use for "
                              "the various vbuckets",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketAuxIoTask},
              {.id = StatGroupId::Eviction,
               .key = "eviction",
               .description = "Get eviction related stats",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Hash,
               .key = "hash",
               .description = "Hash stats provide information on your vbucket "
                              "hash tables",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Vbucket,
               .key = "vbucket",
               .description = "vbucket related stats",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::PrevVbucket,
               .key = "prev-vbucket",
               .description = "Get the previous vbstate information",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::VbucketDurabilityState,
               .key = "vbucket-durability-state",
               .description = "Get the durability state for the vbucket",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::VbucketDetails,
               .key = "vbucket-details",
               .description = "Detailed information about a vbucket",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::VbucketSeqno,
               .key = "vbucket-seqno",
               .description = "Get the sequence numbers for a vbucket",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Checkpoint,
               .key = "checkpoint",
               .description = "Checkpoint stats provide detailed information "
                              "on per-vbucket checkpoint datastructure",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::DurabilityMonitor,
               .key = "durability-monitor",
               .description = "Get information from the durability monitor",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Timings,
               .key = "timings",
               .description = "Timing stats provide histogram data from high "
                              "resolution timers over various operations "
                              "within the system.",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::FrequencyCounters,
               .key = "frequency-counters",
               .description = "Histogram describing the MFU values of the "
                              "items in the hashtable.",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Dispatcher,
               .key = "dispatcher",
               .description =
                       "This provides the stats from AUX dispatcher and non-IO "
                       "dispatcher, and from all the reader and writer threads "
                       "running for the specific bucket",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Tasks,
               .key = "tasks",
               .description = "Get information from the tasks in the executor "
                              "pool for the given Bucket",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Scheduler,
               .key = "scheduler",
               .description =
                       "Histograms describing the scheduling overhead times "
                       "and task runtimes incurred by various IO and Non-IO "
                       "tasks respectively",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Runtimes,
               .key = "runtimes",
               .description =
                       "Histograms describing the scheduling overhead times "
                       "and task runtimes incurred by various IO and Non-IO "
                       "tasks respectively",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Memory,
               .key = "memory",
               .description = "This provides various memory-related stats",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Key,
               .key = "key",
               .description = "Get information for a given key",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::KeyById,
               .key = "key-byid",
               .description = "Get information for a given key",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Vkey,
               .key = "vkey",
               .description = "Get information for a given key",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::VkeyById,
               .key = "vkey-byid",
               .description = "Get information for a given key",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Kvtimings,
               .key = "kvtimings",
               .description = "Timing stats provide timing information from "
                              "the underlying storage system",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Kvstore,
               .key = "kvstore",
               .description = "Various low-level stats and timings from the "
                              "underlying KV storage system",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Warmup,
               .key = "warmup",
               .description = "Statistics related to warmup logic",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Info,
               .key = "info",
               .description = "Get the stats-info document",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Config,
               .key = "config",
               .description = "Get the bucket configuration",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::DcpVbtakeover,
               .key = "dcp-vbtakeover",
               .description = "Get the statistics related to VB takeover",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Workload,
               .key = "workload",
               .description = "Some information about the number of shards and "
                              "Executor pool information",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Failovers,
               .key = "failovers",
               .description = "Get failover information",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Diskinfo,
               .key = "diskinfo",
               .description = "Get information from the underlying IO layer",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::DiskFailures,
               .key = "disk-failures",
               .description = "Get disk failures",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::DiskSlowness,
               .key = "disk-slowness",
               .description = "Get a view of pending disk requests",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::_CheckpointDump,
               .key = "_checkpoint-dump",
               .description =
                       "Dump the Checkpoint Manager for the provided vbucket",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::_HashDump,
               .key = "_hash-dump",
               .description = "Dump the hashtable",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::_DurabilityDump,
               .key = "_durability-dump",
               .description = "Dump the Durability Monitor",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::_VbucketDump,
               .key = "_vbucket-dump",
               .description = "Dump the vbucket",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::RangeScans,
               .key = "range-scans",
               .description = "Get information about vbucket range-scans",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Fusion,
               .key = "fusion",
               .description = "Get Fusion state",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::SnapshotDetails,
               .key = "snapshot-details",
               .description =
                       "Get detailed information about vbucket disk snapshots",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::SnapshotStatus,
               .key = "snapshot-status",
               .description = "Get brief status information about one or all "
                              "vbucket disk snapshots",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::SnapshotDeks,
               .key = "snapshot-deks",
               .description =
                       "Get the deks related to all vbucket disk snapshots",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::SnapshotMove,
               .key = "snapshot-move",
               .description =
                       "Get the snapshot move status for one or all vbuckets",
               .privileged = true,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::StatTimings,
               .key = "stat-timings",
               .description = "Get timing information for stat commands",
               .privileged = false,
               .bucket = true,
               .task_id = TaskId::Core_StatsBucketTask},
              {.id = StatGroupId::Threads,
               .key = "threads",
               .description = "Get information about thread numbers",
               .privileged = true,
               .bucket = false,
               .task_id = TaskId::Core_StatsBucketTask},
      }) {
}

StatsGroupManager& StatsGroupManager::getInstance() {
    static StatsGroupManager instance;
    return instance;
}

const StatGroup* StatsGroupManager::doLookup(std::string_view key) {
    for (const auto& e : entries) {
        if (e.key == key) {
            return &e;
        }
    }
    return nullptr;
}

const StatGroup* StatsGroupManager::lookup(std::string_view key) {
    return getInstance().doLookup(key);
}

void StatsGroupManager::iterate(
        std::function<void(const StatGroup&)> callback) {
    for (const auto& e : getInstance().entries) {
        callback(e);
    }
}

const StatGroup* StatsGroupManager::lookup(StatGroupId id) {
    for (const auto& e : entries) {
        if (e.id == id) {
            return &e;
        }
    }
    return nullptr;
}
