#!/usr/bin/env python
"""
Checkpoint config control for ep-engine.
"""

import clitool
from memcacheConstants import ENGINE_PARAM_CHECKPOINT

def set_param(mc, key, val, username=None, password=""):
    if username:
        mc.sasl_auth_plain(username, password)
    mc.set_param(key, val, ENGINE_PARAM_CHECKPOINT)

if __name__ == '__main__':

    c = clitool.CliTool("""
Available params for "set":
    chk_max_items            - Max number of items allowed in a checkpoint
    chk_period               - Time bound (in sec.) on a checkpoint
    inconsistent_slave_chk   - true if we allow a downstream master to receive checkpoint
                               begin/end messages from the upstream master
    item_num_based_new_chk   - true if a new checkpoint can be created based on
                               the number of items in the open checkpoint
    keep_closed_chks         - true if we want to keep closed checkpoints in memory
                               as long as the current memory usage is below high water mark
    max_checkpoints          - Max number of checkpoints allowed per vbucket""")

    c.addCommand('set', set_param, 'set param value [username password]')
    c.execute()
