#!/usr/bin/env python

import clitool
import mc_bin_client
from memcacheConstants import ENGINE_PARAM_TAP

def set_param(mc, key, val, username=None, password=""):
    if key == 'tap_throttle_queue_cap' and val == 'infinite':
        val = '-1'

    try:
        if username:
            mc.sasl_auth_plain(username, password)
        mc.set_param(key, val, ENGINE_PARAM_TAP)
    except mc_bin_client.MemcachedError as error:
        print 'Error: %s' % error.msg

if __name__ == '__main__':

    c = clitool.CliTool("""
Available params for "set":
    tap_keepalive           - Seconds to hold a named tap connection
    tap_throttle_queue_cap  - Max disk write queue size to throttle tap streams
                              ('infinite' means no cap)
    tap_throttle_threshold  - Percentage of memory in use to throttle tap streams
    """)

    c.addCommand('set', set_param, 'set param value [username password]')
    c.execute()
