#! /bin/sh
# A really really simple wrapper on top of dtrace that allows me to
# pass along the .lo files (and have it generate a .lo file) so
# that it integrates a little bit better with automake etc.
cmd=
looutfile=
outfile=

for f in $*
do
  echo $f | grep '.lo$' > /dev/null
  if [ $? -eq 0 ]
  then
    if [ "x$looutfile" = "x" ]
    then
       looutfile=$f
       outfile=`basename $f`
       outfile=.libs/`echo $outfile | sed -e 's,lo$,o,g'`
       cmd="$cmd `dirname $f`/$outfile"
    else
       set -e
       dir=`dirname $f`
       fname=`grep '^pic_object=' $f | cut -f 2 -d\'`
       cmd="$cmd $dir/$fname"
       set +e
    fi
  else
    cmd="$cmd $f"
  fi
done

# remove the old lo file
rm -f $looutfile

echo $cmd
$cmd
if [ $? -ne 0 ]
then
  exit $?
fi

# generate a new lo file
ltversion=`./libtool --version | head -1`
cat > $looutfile <<EOF
# Generated by $ltversion
pic_object='$outfile'
non_pic_object=none
EOF
