#!/usr/bin/env python3
"""

  Copyright 2021-Present Couchbase, Inc.

Use of this software is governed by the Business Source License included in
the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
file, in accordance with the Business Source License, use of this software will
be governed by the Apache License, Version 2.0, included in the file
licenses/APL2.txt.

"""

from cli_auth_utils import get_authed_clitool, cmd_decorator
import mc_bin_client


@cmd_decorator
def listvb(mc):
    vbs = mc.stats('vbucket')
    for (vb, state) in sorted(list(vbs.items())):
        print("vbucket", vb[3:], state)


@cmd_decorator
def setvb(mc, vbid, vbstate, value):
    mc.set_vbucket_state(int(vbid), vbstate, value)


@cmd_decorator
def rmvb(mc, vbid):
    mc.delete_vbucket(int(vbid))


@cmd_decorator
def mountvb(mc, vbid, value):
    mc.mount_vbucket(int(vbid), value)


@cmd_decorator
def stop_fusion_uploader(mc, vbucket, force=False):
    mc.stop_fusion_uploader(int(vbucket))
    print(f'Fusion uploader stopped for vb:{vbucket}')


if __name__ == '__main__':
    usage = """
stop_fusion_uploader:
  1 parameter
    vbucket    - ID of the vbucket to stop fusion uploader on
  Example: Stop fusion uploader on vbucket 23
    cbvbucketctl host:port -b default stop_fusion_uploader 23
"""

    c = get_authed_clitool(usage, allBuckets=False)

    c.addCommand('list', listvb, 'list')
    c.addCommand(
        'set', setvb, 'set <vbid> active|replica|pending|dead <value>')
    c.addCommand('rm', rmvb, 'rm <vbid>')
    c.addCommand('mount', mountvb, 'mount <vbid> <value>')
    c.addCommand('stop_fusion_uploader', stop_fusion_uploader,
                 'stop_fusion_uploader <vbid>')

    c.execute()
