#!/usr/bin/env python3

#   Copyright 2019-Present Couchbase, Inc.
#
#   Use of this software is governed by the Business Source License included
#   in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
#   in that file, in accordance with the Business Source License, use of this
#   software will be governed by the Apache License, Version 2.0, included in
#   the file licenses/APL2.txt.
#

# Tool to merge multiple KV-Engine trace files into a single file, for
# example to aggregate mutliple node (memcached) traces into a single file.

import argparse
import json
import sys

parser = argparse.ArgumentParser(
    description='Merge two or more KV-Engine trace files into a single file.')
parser.add_argument('infile', nargs='+', type=argparse.FileType('r'),
                                        default=sys.stdin)
parser.add_argument('-o', '--outfile', nargs='?', type=argparse.FileType('w'),
                                        default=sys.stdout)
args = parser.parse_args()

events = []
for input in args.infile:
    events.extend(json.load(input)['traceEvents'])

json.dump({'traceEvents': events}, args.outfile)
