#!/usr/bin/env python3

#   Copyright 2019 Couchbase, Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# Tool to merge multiple KV-Engine trace files into a single file, for
# example to aggregate mutliple node (memcached) traces into a single file.

import argparse
import json
import sys

parser = argparse.ArgumentParser(
    description='Merge two or more KV-Engine trace files into a single file.')
parser.add_argument('infile', nargs='+', type=argparse.FileType('r'),
                                        default=sys.stdin)
parser.add_argument('-o', '--outfile', nargs='?', type=argparse.FileType('w'),
                                        default=sys.stdout)
args = parser.parse_args()

events = []
for input in args.infile:
    events.extend(json.load(input)['traceEvents'])

json.dump({'traceEvents': events}, args.outfile)
