#!/usr/bin/env python

import os
import sys
import exceptions
import string
import random

try:
    import sqlite3
except:
    sys.exit("ERROR: %s requires sqlite3 for Python." %
              (os.path.basename(sys.argv[0])))

def main():
    random.seed(0)
    db = sqlite3.connect('mbbackup-0001.mbb')
    db.text_factory = str
    createSchema(db)
    print 'Generating mbbackup-0001.mbb'
    generate(db, 10, 0, 1000, 10000, 32767)
    db.close()
    print 'Generating mbbackup-0002.mbb'
    db = sqlite3.connect('mbbackup-0002.mbb')
    db.text_factory = str
    createSchema(db)
    generate(db, 10, 1000, 2000, 10000, 32767)
    db.close()

def generate(db, maxvbid, cpointoffset,  maxcheckpoints, maxoperations, maxsize):
    insert_cpoint_state = "INSERT into cpoint_state" \
                "(vbucket_id, cpoint_id, prev_cpoint_id, state, source, updated_at)" \
                " VALUES (?, ?, ?, ?, ?, ?)"
    insert_cpoint_op = "INSERT into cpoint_op" \
            "(vbucket_id, cpoint_id, seq, op, key, flg, exp, cas, val)" \
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"
    for vbucketId in range(maxvbid):
        cid = cpointoffset
        while cid < maxcheckpoints:
            state = 'closed'
            if random.randint(0, 1000) == 666:
                state = 'open'
            db.execute(insert_cpoint_state, (vbucketId, cid, '0', state, 'notused', 'notused'))
            cid = cid + 1

        db.commit()

    seq = 0
    while seq < maxoperations:
        vbucketId = random.randint(0, maxvbid)
        checkpointId = random.randint(cpointoffset, maxcheckpoints)
        seq = seq + 1
        cmdOp = 'm'
        key = ''.join(random.choice(string.letters + string.digits) for i in xrange(random.randint(1, 250)))
        val = ''.zfill(random.randint(0, maxsize))
        if random.randint(0, 1000) == 666:
            cmdOp = 'd'
            value = ''

        exp = '0'
        flg = random.randint(0, 0xdeadbeef)
        cas = random.randint(0, 10000000)

        db.execute(insert_cpoint_op, (vbucketId, checkpointId, seq, cmdOp,
                       key, flg, exp, cas, val))
        if seq % 100 == 0:
            db.commit()

    # Add some extra well know items I can update in the test
    db.execute(insert_cpoint_op, (0, maxcheckpoints - 1, seq, 'm',
                       'mykey1', 0xdeadbeef, 0, 0xcafecafe, ''.zfill(1024)))
    db.execute(insert_cpoint_op, (0, maxcheckpoints - 1, seq + 1, 'd',
                       'mykey2', 0xdeadbeef, 0, 0xcafecafe, ''))
    db.execute(insert_cpoint_op, (0, maxcheckpoints - 1, seq + 2, 'm',
                       'mykey3', 0xdeadbeef, 0, 0xcafecafe, ''.zfill(1)))
    db.execute(insert_cpoint_op, (0, maxcheckpoints - 1, seq + 3, 'm',
                       'mykey4', 0xdeadbeef, 1, 0xcafecafe, ''.zfill(1)))
    db.commit()

def createSchema(db):
    db.executescript("""
BEGIN;
DROP TABLE IF EXISTS cpoint_op;
DROP TABLE IF EXISTS cpoint_state;
CREATE TABLE cpoint_op
  (vbucket_id integer, cpoint_id text, seq integer, op text,
   key varchar(250), flg integer, exp integer, cas integer, val text);
CREATE TABLE cpoint_state
  (vbucket_id integer, cpoint_id text, prev_cpoint_id text, state varchar(1),
   source varchar(250), updated_at text);
COMMIT;
""")

if __name__ == '__main__':
    main()
