/* -*- Mode: C++; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*- */
/*
 *     Copyright 2018-Present Couchbase, Inc.
 *
 *   Use of this software is governed by the Business Source License included
 *   in the file licenses/BSL-Couchbase.txt.  As of the Change Date specified
 *   in that file, in accordance with the Business Source License, use of this
 *   software will be governed by the Apache License, Version 2.0, included in
 *   the file licenses/APL2.txt.
 */

#include <mcbp/protocol/opcode.h>
#include <platform/string_hex.h>
#include <algorithm>
#include <cctype>
#include <stdexcept>

namespace cb::mcbp {

bool is_valid_opcode(ClientOpcode opcode) {
    switch (opcode) {
    case ClientOpcode::Get:
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Getq:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Stat:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::Gatq:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::GetReplica:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        return true;
    case ClientOpcode::Invalid:
        break;
    }
    return false;
}

bool is_valid_opcode(ServerOpcode opcode) {
    switch (opcode) {
    case ServerOpcode::ClustermapChangeNotification:
    case ServerOpcode::Authenticate:
    case ServerOpcode::ActiveExternalUsers:
    case ServerOpcode::GetAuthorization:
        return true;
    }
    return false;
}

bool is_supported_opcode(ClientOpcode opcode) {
    switch (opcode) {
    case ClientOpcode::Get:
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Getq:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Stat:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::Gatq:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::GetReplica:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        return true;
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::Invalid:
        break;
    }
    return false;
}

bool is_durability_supported(ClientOpcode opcode) {
    using cb::mcbp::ClientOpcode;

    switch (opcode) {
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
        return true;

    case ClientOpcode::Get:
    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Getq:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::Stat:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Gatq:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::GetReplica:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        return false;

    case ClientOpcode::Invalid:
        break;
    }

    throw std::runtime_error(
            "cb::mcbp::is_durability_supported: Unknown command " +
            cb::to_hex(uint8_t(opcode)));
}

bool is_reorder_supported(ClientOpcode opcode) {
    switch (opcode) {
    case ClientOpcode::Get:
    case ClientOpcode::Getk:
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Gat:
    case ClientOpcode::Touch:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetReplica:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::RangeScanCreate:
        return true;

    case ClientOpcode::Getq:
    case ClientOpcode::Getkq:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Gatq:
    case ClientOpcode::Stat:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Quit:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flush:
    case ClientOpcode::Flushq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        return false;

    case ClientOpcode::Invalid:
        break;
    }

    throw std::runtime_error(
            "cb::mcbp::is_reorder_supported: Unknown command " +
            cb::to_hex(uint8_t(opcode)));
}

bool is_collection_command(ClientOpcode opcode) {
    switch (opcode) {
    case ClientOpcode::Get:
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Getq:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::Gatq:
    case ClientOpcode::GetReplica:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
        return true;

    case ClientOpcode::Observe:
    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Stat:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    // MB-39650: DCP input are not collection commands in this context. They do
    // represent changes to collections, but they are not privilege checked
    // against anything other than bucket level Privilege::DcpConsumer there
    // is no concept of allowing some collections and failing another for DCP
    // input.
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        return false;
    case ClientOpcode::Invalid:
        break;
    }

    throw std::runtime_error(
            "cb::mcbp::is_collection_command: Unknown command " +
            cb::to_hex(uint8_t(opcode)));
}

bool is_deprecated(ClientOpcode opcode) {
    if (!is_valid_opcode(opcode) || !is_supported_opcode(opcode)) {
        return false;
    }
    switch (opcode) {
    case ClientOpcode::Getq:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::DelqWithMeta:
        return true;

    case ClientOpcode::Get:
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Stat:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::Gatq:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::GetReplica:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::GetMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
    case ClientOpcode::Invalid:
        break;
    }
    return false;
}

bool is_preserve_ttl_supported(ClientOpcode opcode) {
    switch (opcode) {
    case ClientOpcode::Set:
    case ClientOpcode::Setq:
    case ClientOpcode::Replace:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Increment:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrement:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Append:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prepend:
    case ClientOpcode::Prependq:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
        return true;

    case ClientOpcode::Delete:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::Add:
    case ClientOpcode::Get:
    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Getq:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::Stat:
    case ClientOpcode::Addq:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Gatq:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::GetReplica:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::GetKeys:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        return false;

    case ClientOpcode::Invalid:
        break;
    }

    throw std::runtime_error(
            "cb::mcbp::is_preserve_ttl_supported: Unknown command " +
            cb::to_hex(uint8_t(opcode)));
}

bool is_subject_for_throttling(ClientOpcode opcode) {
    switch (opcode) {
    case ClientOpcode::Get:
    case ClientOpcode::Getq:
    case ClientOpcode::Getk:
    case ClientOpcode::Getkq:
    case ClientOpcode::Increment:
    case ClientOpcode::Decrement:
    case ClientOpcode::Set:
    case ClientOpcode::Add:
    case ClientOpcode::Replace:
    case ClientOpcode::Delete:
    case ClientOpcode::Append:
    case ClientOpcode::Prepend:
    case ClientOpcode::Setq:
    case ClientOpcode::Addq:
    case ClientOpcode::Replaceq:
    case ClientOpcode::Deleteq:
    case ClientOpcode::Incrementq:
    case ClientOpcode::Decrementq:
    case ClientOpcode::Appendq:
    case ClientOpcode::Prependq:
    case ClientOpcode::Touch:
    case ClientOpcode::Gat:
    case ClientOpcode::Gatq:
    case ClientOpcode::Rget_Unsupported:
    case ClientOpcode::Rset_Unsupported:
    case ClientOpcode::Rsetq_Unsupported:
    case ClientOpcode::Rappend_Unsupported:
    case ClientOpcode::Rappendq_Unsupported:
    case ClientOpcode::Rprepend_Unsupported:
    case ClientOpcode::Rprependq_Unsupported:
    case ClientOpcode::Rdelete_Unsupported:
    case ClientOpcode::Rdeleteq_Unsupported:
    case ClientOpcode::Rincr_Unsupported:
    case ClientOpcode::Rincrq_Unsupported:
    case ClientOpcode::Rdecr_Unsupported:
    case ClientOpcode::Rdecrq_Unsupported:
    case ClientOpcode::GetReplica:
    case ClientOpcode::GetLocked:
    case ClientOpcode::UnlockKey:
    case ClientOpcode::ObserveSeqno:
    case ClientOpcode::Observe:
    case ClientOpcode::GetMeta:
    case ClientOpcode::GetqMeta:
    case ClientOpcode::SetWithMeta:
    case ClientOpcode::SetqWithMeta:
    case ClientOpcode::AddWithMeta:
    case ClientOpcode::AddqWithMeta:
    case ClientOpcode::DelWithMeta:
    case ClientOpcode::DelqWithMeta:
    case ClientOpcode::ReturnMeta:
    case ClientOpcode::GetRandomKey:
    case ClientOpcode::GetKeys:
    case ClientOpcode::SubdocGet:
    case ClientOpcode::SubdocExists:
    case ClientOpcode::SubdocDictAdd:
    case ClientOpcode::SubdocDictUpsert:
    case ClientOpcode::SubdocDelete:
    case ClientOpcode::SubdocReplace:
    case ClientOpcode::SubdocArrayPushLast:
    case ClientOpcode::SubdocArrayPushFirst:
    case ClientOpcode::SubdocArrayInsert:
    case ClientOpcode::SubdocArrayAddUnique:
    case ClientOpcode::SubdocCounter:
    case ClientOpcode::SubdocMultiLookup:
    case ClientOpcode::SubdocMultiMutation:
    case ClientOpcode::SubdocGetCount:
    case ClientOpcode::SubdocReplaceBodyWithXattr:
        return true;

    case ClientOpcode::Quit:
    case ClientOpcode::Flush:
    case ClientOpcode::Noop:
    case ClientOpcode::Version:
    case ClientOpcode::Stat:
    case ClientOpcode::Quitq:
    case ClientOpcode::Flushq:
    case ClientOpcode::Verbosity:
    case ClientOpcode::Hello:
    case ClientOpcode::SaslListMechs:
    case ClientOpcode::SaslAuth:
    case ClientOpcode::SaslStep:
    case ClientOpcode::IoctlGet:
    case ClientOpcode::IoctlSet:
    case ClientOpcode::ConfigValidate:
    case ClientOpcode::ConfigReload:
    case ClientOpcode::AuditPut:
    case ClientOpcode::AuditConfigReload:
    case ClientOpcode::Shutdown:
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
    case ClientOpcode::SetVbucket:
    case ClientOpcode::GetVbucket:
    case ClientOpcode::DelVbucket:
    case ClientOpcode::TapConnect_Unsupported:
    case ClientOpcode::TapMutation_Unsupported:
    case ClientOpcode::TapDelete_Unsupported:
    case ClientOpcode::TapFlush_Unsupported:
    case ClientOpcode::TapOpaque_Unsupported:
    case ClientOpcode::TapVbucketSet_Unsupported:
    case ClientOpcode::TapCheckpointStart_Unsupported:
    case ClientOpcode::TapCheckpointEnd_Unsupported:
    case ClientOpcode::GetAllVbSeqnos:
    case ClientOpcode::DcpOpen:
    case ClientOpcode::DcpAddStream:
    case ClientOpcode::DcpCloseStream:
    case ClientOpcode::DcpStreamReq:
    case ClientOpcode::DcpGetFailoverLog:
    case ClientOpcode::DcpStreamEnd:
    case ClientOpcode::DcpSnapshotMarker:
    case ClientOpcode::DcpMutation:
    case ClientOpcode::DcpDeletion:
    case ClientOpcode::DcpExpiration:
    case ClientOpcode::DcpFlush_Unsupported:
    case ClientOpcode::DcpSetVbucketState:
    case ClientOpcode::DcpNoop:
    case ClientOpcode::DcpBufferAcknowledgement:
    case ClientOpcode::DcpControl:
    case ClientOpcode::DcpSystemEvent:
    case ClientOpcode::DcpPrepare:
    case ClientOpcode::DcpSeqnoAcknowledged:
    case ClientOpcode::DcpCommit:
    case ClientOpcode::DcpAbort:
    case ClientOpcode::DcpSeqnoAdvanced:
    case ClientOpcode::DcpOsoSnapshot:
    case ClientOpcode::StopPersistence:
    case ClientOpcode::StartPersistence:
    case ClientOpcode::SetParam:
    case ClientOpcode::CreateBucket:
    case ClientOpcode::DeleteBucket:
    case ClientOpcode::ListBuckets:
    case ClientOpcode::SelectBucket:
    case ClientOpcode::EvictKey:
    case ClientOpcode::GetFailoverLog:
    case ClientOpcode::LastClosedCheckpoint:
    case ClientOpcode::DeregisterTapClient_Unsupported:
    case ClientOpcode::ResetReplicationChain_Unsupported:
    case ClientOpcode::SnapshotVbStates_Unsupported:
    case ClientOpcode::VbucketBatchCount_Unsupported:
    case ClientOpcode::CreateCheckpoint:
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
    case ClientOpcode::EnableTraffic:
    case ClientOpcode::DisableTraffic:
    case ClientOpcode::Ifconfig:
    case ClientOpcode::ChangeVbFilter_Unsupported:
    case ClientOpcode::CheckpointPersistence_Unsupported:
    case ClientOpcode::CompactDb:
    case ClientOpcode::SetClusterConfig:
    case ClientOpcode::GetClusterConfig:
    case ClientOpcode::SeqnoPersistence:
    case ClientOpcode::CollectionsSetManifest:
    case ClientOpcode::CollectionsGetManifest:
    case ClientOpcode::CollectionsGetID:
    case ClientOpcode::CollectionsGetScopeID:
    case ClientOpcode::SetDriftCounterState_Unsupported:
    case ClientOpcode::GetAdjustedTime_Unsupported:
    case ClientOpcode::Scrub:
    case ClientOpcode::IsaslRefresh:
    case ClientOpcode::SslCertsRefresh:
    case ClientOpcode::GetCmdTimer:
    case ClientOpcode::SetCtrlToken:
    case ClientOpcode::GetCtrlToken:
    case ClientOpcode::UpdateExternalUserPermissions:
    case ClientOpcode::RbacRefresh:
    case ClientOpcode::AuthProvider:
    case ClientOpcode::DropPrivilege:
    case ClientOpcode::AdjustTimeofday:
    case ClientOpcode::EwouldblockCtl:
    case ClientOpcode::GetErrorMap:
    case ClientOpcode::RangeScanCreate:
    case ClientOpcode::RangeScanContinue:
    case ClientOpcode::RangeScanCancel:
        // should not be throttled
        return false;

    case ClientOpcode::Invalid:
        break;
    }

    throw std::runtime_error(
            "cb::mcbp::is_subject_for_throttling: Unknown command " +
            cb::to_hex(uint8_t(opcode)));
}

std::ostream& operator<<(std::ostream& out,
                         const cb::mcbp::ClientOpcode& opcode) {
    out << ::to_string(opcode);
    return out;
}

std::ostream& operator<<(std::ostream& out,
                         const cb::mcbp::ServerOpcode& opcode) {
    out << ::to_string(opcode);
    return out;
}

} // namespace cb::mcbp

std::string to_string(cb::mcbp::ClientOpcode opcode) {
    using namespace cb::mcbp;

    switch (opcode) {
    case ClientOpcode::Get:
        return "GET";
    case ClientOpcode::Set:
        return "SET";
    case ClientOpcode::Add:
        return "ADD";
    case ClientOpcode::Replace:
        return "REPLACE";
    case ClientOpcode::Delete:
        return "DELETE";
    case ClientOpcode::Increment:
        return "INCREMENT";
    case ClientOpcode::Decrement:
        return "DECREMENT";
    case ClientOpcode::Quit:
        return "QUIT";
    case ClientOpcode::Flush:
        return "FLUSH";
    case ClientOpcode::Getq:
        return "GETQ";
    case ClientOpcode::Noop:
        return "NOOP";
    case ClientOpcode::Version:
        return "VERSION";
    case ClientOpcode::Getk:
        return "GETK";
    case ClientOpcode::Getkq:
        return "GETKQ";
    case ClientOpcode::Append:
        return "APPEND";
    case ClientOpcode::Prepend:
        return "PREPEND";
    case ClientOpcode::Stat:
        return "STAT";
    case ClientOpcode::Setq:
        return "SETQ";
    case ClientOpcode::Addq:
        return "ADDQ";
    case ClientOpcode::Replaceq:
        return "REPLACEQ";
    case ClientOpcode::Deleteq:
        return "DELETEQ";
    case ClientOpcode::Incrementq:
        return "INCREMENTQ";
    case ClientOpcode::Decrementq:
        return "DECREMENTQ";
    case ClientOpcode::Quitq:
        return "QUITQ";
    case ClientOpcode::Flushq:
        return "FLUSHQ";
    case ClientOpcode::Appendq:
        return "APPENDQ";
    case ClientOpcode::Prependq:
        return "PREPENDQ";
    case ClientOpcode::Verbosity:
        return "VERBOSITY";
    case ClientOpcode::Touch:
        return "TOUCH";
    case ClientOpcode::Gat:
        return "GAT";
    case ClientOpcode::Gatq:
        return "GATQ";
    case ClientOpcode::Hello:
        return "HELLO";
    case ClientOpcode::SaslListMechs:
        return "SASL_LIST_MECHS";
    case ClientOpcode::SaslAuth:
        return "SASL_AUTH";
    case ClientOpcode::SaslStep:
        return "SASL_STEP";
    case ClientOpcode::IoctlGet:
        return "IOCTL_GET";
    case ClientOpcode::IoctlSet:
        return "IOCTL_SET";
    case ClientOpcode::ConfigValidate:
        return "CONFIG_VALIDATE";
    case ClientOpcode::ConfigReload:
        return "CONFIG_RELOAD";
    case ClientOpcode::AuditPut:
        return "AUDIT_PUT";
    case ClientOpcode::AuditConfigReload:
        return "AUDIT_CONFIG_RELOAD";
    case ClientOpcode::Shutdown:
        return "SHUTDOWN";
    case ClientOpcode::SetBucketComputeUnitThrottleLimits:
        return "SET_BUCKET_COMPUTE_UNIT_THROTTLE_LIMITS";
    case ClientOpcode::Rget_Unsupported:
        return "RGET";
    case ClientOpcode::Rset_Unsupported:
        return "RSET";
    case ClientOpcode::Rsetq_Unsupported:
        return "RSETQ";
    case ClientOpcode::Rappend_Unsupported:
        return "RAPPEND";
    case ClientOpcode::Rappendq_Unsupported:
        return "RAPPENDQ";
    case ClientOpcode::Rprepend_Unsupported:
        return "RPREPEND";
    case ClientOpcode::Rprependq_Unsupported:
        return "RPREPENDQ";
    case ClientOpcode::Rdelete_Unsupported:
        return "RDELETE";
    case ClientOpcode::Rdeleteq_Unsupported:
        return "RDELETEQ";
    case ClientOpcode::Rincr_Unsupported:
        return "RINCR";
    case ClientOpcode::Rincrq_Unsupported:
        return "RINCRQ";
    case ClientOpcode::Rdecr_Unsupported:
        return "RDECR";
    case ClientOpcode::Rdecrq_Unsupported:
        return "RDECRQ";
    case ClientOpcode::SetVbucket:
        return "SET_VBUCKET";
    case ClientOpcode::GetVbucket:
        return "GET_VBUCKET";
    case ClientOpcode::DelVbucket:
        return "DEL_VBUCKET";
    case ClientOpcode::TapConnect_Unsupported:
        return "TAP_CONNECT";
    case ClientOpcode::TapMutation_Unsupported:
        return "TAP_MUTATION";
    case ClientOpcode::TapDelete_Unsupported:
        return "TAP_DELETE";
    case ClientOpcode::TapFlush_Unsupported:
        return "TAP_FLUSH";
    case ClientOpcode::TapOpaque_Unsupported:
        return "TAP_OPAQUE";
    case ClientOpcode::TapVbucketSet_Unsupported:
        return "TAP_VBUCKET_SET";
    case ClientOpcode::TapCheckpointStart_Unsupported:
        return "TAP_CHECKPOINT_START";
    case ClientOpcode::TapCheckpointEnd_Unsupported:
        return "TAP_CHECKPOINT_END";
    case ClientOpcode::GetAllVbSeqnos:
        return "GET_ALL_VB_SEQNOS";
    case ClientOpcode::DcpOpen:
        return "DCP_OPEN";
    case ClientOpcode::DcpAddStream:
        return "DCP_ADD_STREAM";
    case ClientOpcode::DcpCloseStream:
        return "DCP_CLOSE_STREAM";
    case ClientOpcode::DcpStreamReq:
        return "DCP_STREAM_REQ";
    case ClientOpcode::DcpGetFailoverLog:
        return "DCP_GET_FAILOVER_LOG";
    case ClientOpcode::DcpStreamEnd:
        return "DCP_STREAM_END";
    case ClientOpcode::DcpSnapshotMarker:
        return "DCP_SNAPSHOT_MARKER";
    case ClientOpcode::DcpMutation:
        return "DCP_MUTATION";
    case ClientOpcode::DcpDeletion:
        return "DCP_DELETION";
    case ClientOpcode::DcpFlush_Unsupported:
        return "DCP_FLUSH";
    case ClientOpcode::DcpExpiration:
        return "DCP_EXPIRATION";
    case ClientOpcode::DcpSetVbucketState:
        return "DCP_SET_VBUCKET_STATE";
    case ClientOpcode::DcpNoop:
        return "DCP_NOOP";
    case ClientOpcode::DcpBufferAcknowledgement:
        return "DCP_BUFFER_ACKNOWLEDGEMENT";
    case ClientOpcode::DcpControl:
        return "DCP_CONTROL";
    case ClientOpcode::DcpSystemEvent:
        return "DCP_SYSTEM_EVENT";
    case ClientOpcode::DcpPrepare:
        return "DCP_PREPARE";
    case ClientOpcode::DcpSeqnoAcknowledged:
        return "DCP_SEQNO_ACKNOWLEDGED";
    case ClientOpcode::DcpCommit:
        return "DCP_COMMIT";
    case ClientOpcode::DcpAbort:
        return "DCP_ABORT";
    case ClientOpcode::DcpSeqnoAdvanced:
        return "DCP_SEQNO_ADVANCED";
    case ClientOpcode::DcpOsoSnapshot:
        return "DCP_OSO_SNAPSHOT";
    case ClientOpcode::StopPersistence:
        return "STOP_PERSISTENCE";
    case ClientOpcode::StartPersistence:
        return "START_PERSISTENCE";
    case ClientOpcode::SetParam:
        return "SET_PARAM";
    case ClientOpcode::GetReplica:
        return "GET_REPLICA";
    case ClientOpcode::CreateBucket:
        return "CREATE_BUCKET";
    case ClientOpcode::DeleteBucket:
        return "DELETE_BUCKET";
    case ClientOpcode::ListBuckets:
        return "LIST_BUCKETS";
    case ClientOpcode::SelectBucket:
        return "SELECT_BUCKET";
    case ClientOpcode::ObserveSeqno:
        return "OBSERVE_SEQNO";
    case ClientOpcode::Observe:
        return "OBSERVE";
    case ClientOpcode::EvictKey:
        return "EVICT_KEY";
    case ClientOpcode::GetLocked:
        return "GET_LOCKED";
    case ClientOpcode::UnlockKey:
        return "UNLOCK_KEY";
    case ClientOpcode::GetFailoverLog:
        return "GET_FAILOVER_LOG";
    case ClientOpcode::LastClosedCheckpoint:
        return "LAST_CLOSED_CHECKPOINT";
    case ClientOpcode::ResetReplicationChain_Unsupported:
        return "RESET_REPLICATION_CHAIN";
    case ClientOpcode::DeregisterTapClient_Unsupported:
        return "DEREGISTER_TAP_CLIENT";
    case ClientOpcode::GetMeta:
        return "GET_META";
    case ClientOpcode::GetqMeta:
        return "GETQ_META";
    case ClientOpcode::SetWithMeta:
        return "SET_WITH_META";
    case ClientOpcode::SetqWithMeta:
        return "SETQ_WITH_META";
    case ClientOpcode::AddWithMeta:
        return "ADD_WITH_META";
    case ClientOpcode::AddqWithMeta:
        return "ADDQ_WITH_META";
    case ClientOpcode::SnapshotVbStates_Unsupported:
        return "SNAPSHOT_VB_STATES";
    case ClientOpcode::VbucketBatchCount_Unsupported:
        return "VBUCKET_BATCH_COUNT";
    case ClientOpcode::DelWithMeta:
        return "DEL_WITH_META";
    case ClientOpcode::DelqWithMeta:
        return "DELQ_WITH_META";
    case ClientOpcode::CreateCheckpoint:
        return "CREATE_CHECKPOINT";
    case ClientOpcode::NotifyVbucketUpdate_Unsupported:
        return "NOTIFY_VBUCKET_UPDATE";
    case ClientOpcode::EnableTraffic:
        return "ENABLE_TRAFFIC";
    case ClientOpcode::DisableTraffic:
        return "DISABLE_TRAFFIC";
    case ClientOpcode::Ifconfig:
        return "IFCONFIG";
    case ClientOpcode::ChangeVbFilter_Unsupported:
        return "CHANGE_VB_FILTER";
    case ClientOpcode::CheckpointPersistence_Unsupported:
        return "CHECKPOINT_PERSISTENCE";
    case ClientOpcode::ReturnMeta:
        return "RETURN_META";
    case ClientOpcode::CompactDb:
        return "COMPACT_DB";
    case ClientOpcode::SetClusterConfig:
        return "SET_CLUSTER_CONFIG";
    case ClientOpcode::GetClusterConfig:
        return "GET_CLUSTER_CONFIG";
    case ClientOpcode::GetRandomKey:
        return "GET_RANDOM_KEY";
    case ClientOpcode::SeqnoPersistence:
        return "SEQNO_PERSISTENCE";
    case ClientOpcode::GetKeys:
        return "GET_KEYS";
    case ClientOpcode::CollectionsSetManifest:
        return "COLLECTIONS_SET_MANIFEST";
    case ClientOpcode::CollectionsGetManifest:
        return "COLLECTIONS_GET_MANIFEST";
    case ClientOpcode::CollectionsGetID:
        return "COLLECTIONS_GET_ID";
    case ClientOpcode::CollectionsGetScopeID:
        return "COLLECTIONS_GET_SCOPE_ID";
    case ClientOpcode::SetDriftCounterState_Unsupported:
        return "SET_DRIFT_COUNTER_STATE";
    case ClientOpcode::GetAdjustedTime_Unsupported:
        return "GET_ADJUSTED_TIME";
    case ClientOpcode::SubdocGet:
        return "SUBDOC_GET";
    case ClientOpcode::SubdocExists:
        return "SUBDOC_EXISTS";
    case ClientOpcode::SubdocDictAdd:
        return "SUBDOC_DICT_ADD";
    case ClientOpcode::SubdocDictUpsert:
        return "SUBDOC_DICT_UPSERT";
    case ClientOpcode::SubdocDelete:
        return "SUBDOC_DELETE";
    case ClientOpcode::SubdocReplace:
        return "SUBDOC_REPLACE";
    case ClientOpcode::SubdocArrayPushLast:
        return "SUBDOC_ARRAY_PUSH_LAST";
    case ClientOpcode::SubdocArrayPushFirst:
        return "SUBDOC_ARRAY_PUSH_FIRST";
    case ClientOpcode::SubdocArrayInsert:
        return "SUBDOC_ARRAY_INSERT";
    case ClientOpcode::SubdocArrayAddUnique:
        return "SUBDOC_ARRAY_ADD_UNIQUE";
    case ClientOpcode::SubdocCounter:
        return "SUBDOC_COUNTER";
    case ClientOpcode::SubdocMultiLookup:
        return "SUBDOC_MULTI_LOOKUP";
    case ClientOpcode::SubdocMultiMutation:
        return "SUBDOC_MULTI_MUTATION";
    case ClientOpcode::SubdocGetCount:
        return "SUBDOC_GET_COUNT";
    case ClientOpcode::SubdocReplaceBodyWithXattr:
        return "SUBDOC_REPLACE_BODY_WITH_XATTR";
    case ClientOpcode::Scrub:
        return "SCRUB";
    case ClientOpcode::IsaslRefresh:
        return "ISASL_REFRESH";
    case ClientOpcode::SslCertsRefresh:
        return "SSL_CERTS_REFRESH";
    case ClientOpcode::GetCmdTimer:
        return "GET_CMD_TIMER";
    case ClientOpcode::SetCtrlToken:
        return "SET_CTRL_TOKEN";
    case ClientOpcode::GetCtrlToken:
        return "GET_CTRL_TOKEN";
    case ClientOpcode::UpdateExternalUserPermissions:
        return "UPDATE_USER_PERMISSIONS";
    case ClientOpcode::RbacRefresh:
        return "RBAC_REFRESH";
    case ClientOpcode::AuthProvider:
        return "AUTH_PROVIDER";
    case ClientOpcode::DropPrivilege:
        return "DROP_PRIVILEGES";
    case ClientOpcode::AdjustTimeofday:
        return "ADJUST_TIMEOFDAY";
    case ClientOpcode::EwouldblockCtl:
        return "EWB_CTL";
    case ClientOpcode::GetErrorMap:
        return "GET_ERROR_MAP";
    case ClientOpcode::RangeScanCreate:
        return "RANGE_SCAN_CREATE";
    case ClientOpcode::RangeScanContinue:
        return "RANGE_SCAN_CONTINUE";
    case ClientOpcode::RangeScanCancel:
        return "RANGE_SCAN_CANCEL";
    case ClientOpcode::Invalid:
        break;
    }

    throw std::invalid_argument(
            "to_string(cb::mcbp::ClientOpcode): Invalid opcode: " +
            std::to_string(int(opcode)));
}

std::string to_string(cb::mcbp::ServerOpcode opcode) {
    using namespace cb::mcbp;
    switch (opcode) {
    case ServerOpcode::ClustermapChangeNotification:
        return "ClustermapChangeNotification";
    case ServerOpcode::Authenticate:
        return "Authenticate";
    case ServerOpcode::ActiveExternalUsers:
        return "ActiveExternalUsers";
    case ServerOpcode::GetAuthorization:
        return "GetAuthorization";
    }
    throw std::invalid_argument(
            "to_string(cb::mcbp::ServerOpcode): Invalid opcode: " +
            std::to_string(int(opcode)));
}

cb::mcbp::ClientOpcode to_opcode(const std::string& string) {
    std::string input;
    std::transform(
            string.begin(), string.end(), std::back_inserter(input), ::toupper);
    // If the user used space between the words, replace with '_'
    std::replace(input.begin(), input.end(), ' ', '_');
    for (int ii = 0; ii < int(cb::mcbp::ClientOpcode::Invalid); ++ii) {
        try {
            auto str = to_string(cb::mcbp::ClientOpcode(ii));
            if (str == input) {
                return cb::mcbp::ClientOpcode(ii);
            }
        } catch (const std::invalid_argument&) {
            // ignore
        }
    }

    throw std::invalid_argument("to_opcode(): unknown opcode: \"" + string +
                                "\"");
}
